/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini.test;

import java.util.Comparator;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.Random;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHinG Jakkaphat
 */
class Person {

    String name;
    String gender;
    int age;

    public Person() {
        Random random = new Random();
        //random Name
        int big_char_name = 90 - 65 + 1;
        int first_name_char1 = random.nextInt(big_char_name) + 65;
        int total_char_name = 10 - 2 + 1;// length firts name or last name (2 to 10)
        int max_fname = random.nextInt(total_char_name) + 2;// length first name
        String firstname = "" + Character.toString((char) first_name_char1);// import charactor
        for (int i = 0; i < max_fname - 1; i++) {
            int name_random = random.nextInt(122 - 97 + 1) + 97;
            firstname += "" + Character.toString((char) name_random);// import
        }
        this.name = firstname;
        //random gender
        int max_gender = 2;
        int Gender_random = random.nextInt(max_gender);
        if (Gender_random == 0) {
            this.gender = "Male";
        } else {
            this.gender = "Female";
        }
        //random age 
        int max_age = 100;
        int Age_random = random.nextInt(max_age) + 1;
        this.age = Age_random;
    }
}

class PersonComparator implements Comparator<Person> {

    // Comparator สำหรับ sort ข้อมูลโดยอิงจาก Age(อายุ) ที่เป็น int ที่ตั้งไว้
    @Override
    public int compare(Person p1, Person p2) {
        if (p1.age > p2.age) {
            return -1; // แบบมากไปน้อยใช้ -1 และ else if เป็น 1
        } else if (p1.age < p2.age) {
            return 1;
        }
        return 0;
    }
}

public class NewJFrame extends javax.swing.JFrame {

    Object[][] data;
    Person[] p;
    String[] header = {"Name", "Gender", "Age"};
    Stack<Person> s1 = new Stack<>();
    // สร้างตัวแปล Stack มาเพื่อจัดเก็บข้อมูลไว้โดยรูปแบบไฟล์ที่เก็บคือ class Person
    Person[] p1; // Arrays B ที่โจทย์พูดถึงคือการสร้างตัวแปล Person ขึ้นมาอีกตัว
    Queue<Person> pq = new PriorityQueue<>(new PersonComparator());
    // สร้างตัวแปลจัดเก็บข้อมูลแบบ PriorityQueue โดยกำหนดรูปแบบในการเก็บเป็น class Person
    // -- เพิ่มเติม --
    // ใน new PersonComparator() ที่ใส่นั้นอย่าลืมสร้าง class Comparator ก่อนหละ
    Person[] p2; // Arrays C ที่โจทย์พูดถึงคือการสร้างตัวแปล Person ขึ้นมาอีกตัว

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Gen 10 Person");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stack Operations");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("PQ Operations");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:'
        data = new Object[10][3];
        p = new Person[10];
        for (int i = 0; i < 10; i++) {
            p[i] = new Person();
            data[i][0] = p[i].name;
            data[i][1] = p[i].gender;
            data[i][2] = p[i].age;
        }
        DefaultTableModel model = new DefaultTableModel(data, header);
        jTable1.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            for (int i = 0; i < 10; i++) {
                s1.push(p[i]);
                // เนื่องจาก class Person ที่เราจัดเก็บเป็น Arrays ดังนั้น
                // รูปแบบในการจัดเก็บก็ควรเป็น Arrays ด้วย
                // -- เพิ่มเติม --
                // เหตุผลที่ไม่ใช้ Object ในการเก็บเนื่องจากต้องนำ Object
                // ไปคืนค่าในตัวแปล Person ก่อนจึงจะเก็บได้ ก็เลยเอา Person ที่มีอยู่แล้วมาใส่สะเลย
                System.out.print(s1);
                // ตรวจสอบความถูกต้องเฉยๆ โดยค่าที่ได้ต้องเป็น [mini.test.Person@76153718, mini.test.Person@f1b58fa, mini.test.Person@78e56c78]
                // รหัสแปลกๆอะแหละ อย่าไปสนใจ
            }
            data = new Object[10][3];
            p1 = new Person[10];
            for (int i = 0; i < 10; i++) {
                p1[i] = s1.pop();
                // พอใช้ s1.pop(); แล้วจะทำให้ค่าใน Arrays Person สลับจากข้อมูลตัวสุดท้าย
                // ขึ้นมาเป็นตัวแรก และตัวแรกจะไปเป็นตัวสุดท้าย
                data[i][0] = p1[i].name;
                data[i][1] = p1[i].gender;
                data[i][2] = p1[i].age;
                System.out.println(p1[i].name); // ตรวจสอบความถูกต้อง
            }
            DefaultTableModel model = new DefaultTableModel(data, header);
            jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please generate the data first", "No data", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            for (int i = 0; i < 10; i++) {
                pq.add(p[i]);
                // เพิ่มค่าจาก Person p แรก เหตุเพราะในกรณีที่มีการกดปุ่ม
                // PriorityQueue จะมีการ sort จากมาไปน้อยได้ทันที
                // หากใช้ Person p1 จาก stack ถ้าเราไม่ stackก่อนแล้วกดปุ่ม
                // PriorityQueue จะ error ทันทีแม้มีข้อมูลแสดงให้เห็นแล้วก็ตาม
            }
            p2 = new Person[10];
            for (int i = 0; i < 10; i++) {
                p2[i] = pq.remove();
                data[i][0] = p2[i].name;
                data[i][1] = p2[i].gender;
                data[i][2] = p2[i].age;
            }
            DefaultTableModel model = new DefaultTableModel(data, header);
            jTable1.setModel(model);
        } catch (Exception e ) {
            JOptionPane.showMessageDialog(this, "Please generate the data first", "No data", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
