/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment4;

import static java.lang.Math.E;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guest-Student
 */

class Dexy {
    public String name;
    public int count_id;
    public int sum_income;
    public Dexy(){
        Random random = new Random();
        //random name
        int big_char_name = 90 - 65 + 1;
        int first_name_char1 = random.nextInt(big_char_name) + 65;
        int second_name_char2 = random.nextInt(big_char_name) + 65;
        int total_char_name = 10 - 2 + 1;// length firts name or last name (2 to 10)
        int max_fname = random.nextInt(total_char_name) + 2;// length first name
        int max_lname = random.nextInt(total_char_name) + 2;// length last name
        String firstname = "" + Character.toString((char) first_name_char1);// import charactor
        for (int i = 0; i < max_fname - 1; i++) {
            int name_random = random.nextInt(122 - 97 + 1) + 97;
            firstname += "" + Character.toString((char) name_random);// import
        }
        String lastname = "" + Character.toString((char) second_name_char2);
        for (int i = 0; i < max_lname - 1; i++) { //why -1 becuase String import first big character
            int name_random = random.nextInt(122 - 97 + 1) + 97;
            lastname += "" + Character.toString((char) name_random);
        }
        this.name = firstname + " " + lastname;
        //random count_id
        int max_id = 1000-100+1;
        this.count_id = random.nextInt(max_id)+100;
        //sum_income
        this.sum_income = this.count_id*65;
    }

    
}



public class NewJFrame extends javax.swing.JFrame {
    Object[][] ob;
    Dexy[] d;
    /**
     * Creates new form NewJFrame
     */
    
    public static Dexy[] addFirst(Dexy[] source){
        Dexy[] da = new Dexy[source.length+1];
        da[0] = new Dexy();
        for(int i=0; i<source.length; i++){
            da[i+1] = source[i];
        }
        return da;
    }
    
    public static Dexy[] addLast(Dexy[] source){
        Dexy[] da = new Dexy[source.length+1];
        da[source.length] = new Dexy();
        for(int i=0; i<source.length; i++){
            da[i] = source[i];
        }
        return da;
    }
    
    
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dynamic Array - 650710673 - jakkaphat katchapong");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "CountID", "SumIncome"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Gen Object");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add First");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add Last");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sort");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        d = new Dexy[10];
        ob = new Object[10][3];
        for(int i=0; i<10; i++){
            d[i] = new Dexy();
            ob[i][0] = d[i].name;
            ob[i][1] = d[i].count_id;
            ob[i][2] = d[i].sum_income;
        }
        System.out.println("Generate complete"+"/"+d.length);
        String[] header = {"Name","CountID","SumIncome"};
        DefaultTableModel model = new DefaultTableModel(ob,header);
        jTable1.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] header = {"Name","CountID","SumIncome"};
        ob = new Object[11][3];
        d = addFirst(d);
        System.out.println(d.length);
        for(int i=0; i<d.length; i++){
            ob[i][0] = d[i].name;
            ob[i][1] = d[i].count_id;
            ob[i][2] = d[i].sum_income;
        }
        System.out.println("AddFirst complete");
        DefaultTableModel model = new DefaultTableModel(ob,header);
        jTable1.setModel(model);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String[] header = {"Name","CountID","SumIncome"};
        ob = new Object[12][3];
        d = addLast(d);
        System.out.println(d.length);
        for(int i=0; i<d.length; i++){
            ob[i][0] = d[i].name;
            ob[i][1] = d[i].count_id;
            ob[i][2] = d[i].sum_income;
        }
        System.out.println("AddLast complete");
        DefaultTableModel model = new DefaultTableModel(ob,header);
        jTable1.setModel(model);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (d == null) {
            JOptionPane.showMessageDialog(this, "Please generate the data first", "No data", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Select the field to sort by
        String[] fields = {"Name","CountID","SumIncome"};
        String selectedField = (String) JOptionPane.showInputDialog(this, "Select a field to sort:", "Sort by", JOptionPane.PLAIN_MESSAGE, null, fields, fields[0]);

        // Check if the user selected a field
        if (selectedField != null) {
            int fieldIndex = -1;
            switch (selectedField) {
                case "CountID":
                    fieldIndex = 0;
                    break;
                case "Name":
                    fieldIndex = 1;
                    break;
                case "SumIncome":
                    fieldIndex = 2;
                    break;
            }

            // Sort the data based on the selected field
            sortDataByField(fieldIndex);

            // Convert the sorted Employee array to a 2D Object array for the table
            Object[][] sortedData = new Object[d.length][3];
            for (int i = 0; i < d.length; i++) {
                sortedData[i][0] = d[i].name;
                sortedData[i][1] = d[i].count_id;
                sortedData[i][2] = d[i].sum_income;
            }

            // Update the table model with the sorted data
            String[] header = {"Name","CountID","SumIncome"};
            DefaultTableModel model = new DefaultTableModel(sortedData, header);
            System.out.println("Sort complete");
            jTable1.setModel(model);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    
    private void sortDataByField(int fieldIndex) {
        // Use Arrays.sort() to sort the Employee array based on the selected field
        Arrays.sort(d, new Comparator<Dexy>() {
            @Override
            public int compare(Dexy emp1, Dexy emp2) {
                // Use the fieldIndex to determine which field to compare
                switch (fieldIndex) {
                    case 0:
                        return Integer.compare(emp1.count_id, emp2.count_id);
                    case 1:
                        return emp1.name.compareTo(emp2.name);
                    case 2:
                        return Integer.compare(emp1.sum_income, emp2.sum_income);
                    default:
                        return 0;
                }
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
