package javaapplication24;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.io.Serializable;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

class Traveler implements Serializable {

    private String passportId;
    private String name;
    private String gender;
    private int age;
    private String origin;
    private String destination;

    // Overload constructor
    public Traveler(String p, String n, String g, int a, String o, String d){
        passportId = p;
        name = n;
        gender = g;
        age = a;
        origin = o;
        destination = d;
    }
    
    // Overriden Default constructor
    public Traveler() {
        String str1 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String str2 = "0123456789";

        Random r = new Random();
        String temp = "";

        // Generate a random passportID string
        for (int i = 0; i < 2; i++) {
            temp += str1.charAt(r.nextInt(str1.length()));
        }
        for (int i = 0; i < 4; i++) {
            temp += str2.charAt(r.nextInt(str2.length()));
        }
        this.passportId = temp;

        // Generate a random name
        temp = "";
        String str3 = "abcdefghijklmnopqrstuvwxyz";
        // firstname
        int n = r.nextInt(9) + 2;
        for (int i = 0; i < n; i++) {
            if (i == 0) // capital letter
            {
                temp += str1.charAt(r.nextInt(str1.length()));
            } else {
                temp += str3.charAt(r.nextInt(str3.length()));
            }
        }
        temp += " ";
        // lastname
        n = r.nextInt(9) + 2;
        for (int i = 0; i < n; i++) {
            if (i == 0) {
                temp += str1.charAt(r.nextInt(str1.length()));
            } else {
                temp += str3.charAt(r.nextInt(str3.length()));
            }
        }
        this.name = temp;

        // Generate a random gender
        String[] str4 = {"Male", "Female"};
        this.gender = str4[r.nextInt(str4.length)];

        // Generate a random int for the age
        this.age = r.nextInt(100) + 1;

        // Generate a random origin
        String[] str5 = {"Japan", "China", "USA", "Australia", "Canada", "Russia", "India"};
        this.origin = str5[r.nextInt(str5.length)];

        // Generate a random destination
        String[] str6 = {"Bangkok", "Pattaya", "Koh-samui", "Phuket", "Burirum"};
        this.destination = str6[r.nextInt(str6.length)];
    }

    public String toString() {
        return passportId + "," + name + "," + gender + "," + age + "," + origin + "," + destination;
    }

}

public class NewJFrame extends javax.swing.JFrame {

    Object[][] data;
    Traveler[] t;

    public void reset() {
        String[] header = {"PassportID", "Name", "Gender", "Age", "Origin", "Destination"};
        data = null;
        t = null;
        DefaultTableModel model = new DefaultTableModel(data, header);
        jTable1.setModel(model);
    }

    public NewJFrame() {
        initComponents();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("071234-Mr.S: Assignment-2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Gen Traveler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Save 1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Save 2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Load");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(11, 11, 11)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Generate 10 travelers' data and show in the jTable
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        data = new Object[10][];
        t = new Traveler[10];
        for (int i = 0; i < 10; i++) {
            t[i] = new Traveler();
            data[i] = t[i].toString().split(",");
        }
        String[] header = {"PassportID", "Name", "Gender", "Age", "Origin", "Destination"};
        DefaultTableModel model = new DefaultTableModel(data, header);
        jTable1.setModel(model);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Save 1: Plain text
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (data != null) {
            try {
                FileWriter fileWriter = new FileWriter("data.txt");
                PrintWriter printWriter = new PrintWriter(fileWriter);
                for (Traveler x : t) {
                    printWriter.println(x.toString());
                }
                printWriter.close();
                fileWriter.close();

                JOptionPane.showMessageDialog(this, "Plain text data has been saved successfully", "Save 1", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) {
            };
        } else {
            JOptionPane.showMessageDialog(this, "Please generate the data first", "No data", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Save 2:  Serialization
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (data != null) {
            try {
                FileOutputStream fos = new FileOutputStream("data.ser");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(t);
                oos.close();
                fos.close();
                JOptionPane.showMessageDialog(this, "Serialization data has been saved successfully", "Save 2", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
            };
        } else {
            JOptionPane.showMessageDialog(this, "Please generate the data first", "No data", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    // Load
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        boolean dataOk = true;

        try {
            FileReader fileReader = new FileReader("data.txt");
            BufferedReader reader = new BufferedReader(fileReader);
            Traveler[] temp = new Traveler[10];
            for (int i = 0; i < 10; i++) {
                String[] str = reader.readLine().split(",");
                temp[i] = new Traveler(str[0], str[1], str[2], Integer.parseInt(str[3]), str[4], str[5]);
            }
            t = temp;
            reader.close();
            fileReader.close();

    }//GEN-LAST:event_jButton5ActionPerformed

        
        catch (Exception ep) {

            try {

                FileInputStream fis = new FileInputStream("data.ser");
                ObjectInputStream ois = new ObjectInputStream(fis);
                Traveler[] temp = new Traveler[10];
                temp = (Traveler[]) ois.readObject();
                ois.close();
                fis.close();
                t = temp;
            } catch (Exception es) {
                JOptionPane.showMessageDialog(this, "Please generate and save the data first", "No data file", JOptionPane.WARNING_MESSAGE);
                dataOk = false;
            };

        };

        if (dataOk) {
            data = new Object[10][];
            for (int i = 0; i < 10; i++) {
                data[i] = t[i].toString().split(",");
            }
            String[] header = {"PassportID", "Name", "Gender", "Age", "Origin", "Destination"};
            DefaultTableModel model = new DefaultTableModel(data, header);
            jTable1.setModel(model);

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
